/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalprogramacioniii;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author DBTecnología
 */
public class Interfaz extends JFrame {

    public static void crearYMostrarGUI(){
    JFrame frame = new JFrame ("Autentificacion de usuario");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setSize(300, 200);
    
    JButton botonRegistrar = new JButton ("Registrarse");
    JButton botonIniciar = new JButton ("Iniciar sesion");
    
    botonRegistrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mostrarDialogoDeRegistro(frame);
            }
    });
    botonIniciar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                mostrarDialogoDeInicio(frame);
            }
    });
    JPanel panel = new JPanel();
    panel.setLayout(new GridLayout(2, 1, 10, 10));
    panel.add(botonRegistrar);
    panel.add(botonIniciar);
    
    frame.add(panel, BorderLayout.CENTER);
    frame.setVisible(true);
}
    private static void mostrarDialogoDeRegistro(JFrame parentFrame){
    JDialog dialogoDeRegistro = new JDialog(parentFrame, "Registro", true);
    dialogoDeRegistro.setSize(300, 200);
    dialogoDeRegistro.setLayout(new GridLayout(3, 2, 10, 10));
    
    JLabel nombreLabel = new JLabel("Nombre de Usuario: ");
    JTextField nombreField = new JTextField();
    JLabel contraLabel = new JLabel("Contrasenia: ");
    JTextField contraField = new JTextField();
    JLabel correoLabel = new JLabel("Correo electronico: ");
    JTextField correoField = new JTextField();
    JButton botonRegistrar = new JButton("Registrarse");
    
    botonRegistrar.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e){
            String nombreUsuario = nombreField.getText();
            String contraseña = contraField.getText();
            String correo = correoField.getText();
            JOptionPane.showMessageDialog(dialogoDeRegistro, "Se logro registrar correctamente!!");
            dialogoDeRegistro.dispose();
        }
    });
    dialogoDeRegistro.add(nombreLabel);
    dialogoDeRegistro.add(nombreField);
    dialogoDeRegistro.add(contraLabel);
    dialogoDeRegistro.add(contraField);
    dialogoDeRegistro.add(correoLabel);
    dialogoDeRegistro.add(new JLabel());
    dialogoDeRegistro.add(contraField);
    
    dialogoDeRegistro.setVisible(true);
}
    
    private static void mostrarDialogoDeInicio(JFrame parentFrame){
    JDialog dialogoDeInicio = new JDialog(parentFrame, "Iniciar Sesion", true);
    dialogoDeInicio.setSize(300, 200);
    dialogoDeInicio.setLayout(new GridLayout(3, 2, 10, 10));
        
    JLabel nombreLabel = new JLabel ("Nombre de usuario: ");
    JTextField nombreField = new JTextField();
    JLabel contraLabel = new JLabel ("Contrasela:");
    JTextField contraField = new JTextField();
    JButton botonIniciar = new JButton ("Iniciar sesion");
    
    botonIniciar.addActionListener(new ActionListener(){
       @Override
       public void actionPerformed(ActionEvent e){
           String nombreUsuario = nombreField.getText();
           String contraseña = contraField.getText();
           JOptionPane.showMessageDialog(dialogoDeInicio, "Se logro iniciar sesion correctamente");
           dialogoDeInicio.dispose();
       }
    });
    dialogoDeInicio.add(nombreLabel);
    dialogoDeInicio.add(nombreField);    
    dialogoDeInicio.add(contraLabel);    
    dialogoDeInicio.add(contraField);
    dialogoDeInicio.add(new JLabel());
    dialogoDeInicio.add(botonIniciar);
    
    dialogoDeInicio.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
